name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  schedule:
      - cron: '*/1 * * * *'

jobs:
  build:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      # Reference a specific commit
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      # Reference the major version of a release
      - uses: actions/checkout@v4
      # Reference a specific version
      - uses: actions/checkout@v4.2.0
      # Reference a branch
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: 3.12

      - name: Install required dependencies
        run: |
          python -m pip install pytz  # Install any required Python packages

      - name: Build the greeting JSON
        run: |
          python greeting.py

      # - name: Build the events JSON
      #   run: |
      #     python events.py

      - name: Push to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true